version: "{build}"
skip_non_tags: true
image:
  - Ubuntu

install:
  - |
    cat << EOF | sudo tee /etc/apt/preferences.d/p7zip.pref
    Package: *
    Pin: release n=bionic
    Pin-Priority: -10

    Package: p7zip
    Pin: release n=bionic
    Pin-Priority: 500

    Package: p7zip-full
    Pin: release n=bionic
    Pin-Priority: 500

    Package: p7zip-rar
    Pin: release n=bionic
    Pin-Priority: 500
    EOF
  - sudo sh -c 'echo "deb http://us-central1.gce.archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse" >> /etc/apt/sources.list'
  - sudo apt update
  - sudo apt -y install p7zip-full

build_script:
  - ./build.sh

artifacts:
  - path: '*.zip'

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: JFcBo1SYmjlb31U5qawX2pSSCXfnGYTjjjyr1Gv4DWnmiQQ43GT5RFFH2jS4lt+P
  artifact: /.*\.zip/
  draft: true
  prerelease: false
